VAGRANTFILE_API_VERSION = "2"
BOX_IMAGE = "perk/ubuntu-2204-arm64"
NODE_COUNT = 3
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'qemu'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"

      subconfig.vm.provider "qemu" do |qe|
        qe.ssh_port = "#{60021 + i}"
        qe.ssh_port_auto_correct = true
      end
    end
  end
end